image: "python:3.7"

# job that runs the Django unit tests
unit_tests:
  script:
  
    # install the required apis for Django
    - pip install --upgrade pip
    - pip install -r requirements
    
    # perform the unit tests
    - cd Website/Ogre
    - python3 manage.py test 
  tags:
    - docker

# job for testing code quality using flake8 linting tool
linter:
  script:
    - pip install flake8
    
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --ignore=F821 --select=E9,F63,F7,F82 --show-source --statistics
    
    # exit-zero treats all errors as warnings. The editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  tags:
    - docker
