# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-13 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_remove_student_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Student_ID',
            new_name='StudentID',
        ),
    ]
