# Generated by Django 2.1.7 on 2020-01-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_auto_20191228_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofileinfo',
            name='StudentID',
            field=models.CharField(help_text='Required. the StudentID must your moodle studentID', max_length=8, null=True, unique=True),
        ),
    ]
