# Generated by Django 2.1.7 on 2020-03-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_auto_20200310_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofileinfo',
            name='StudentID',
            field=models.CharField(help_text='Please enter your Student ID you use for Moodle.', max_length=8, null=True, unique=True),
        ),
    ]
