# Generated by Django 3.0.2 on 2020-02-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_auto_20200129_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatarID', models.IntegerField(max_length=8, null=True, unique=True)),
                ('avatar', models.ImageField(upload_to=None)),
            ],
        ),
    ]
