# Generated by Django 3.0.2 on 2020-02-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_auto_20200129_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofileinfo',
            name='currentPoints',
        ),
        migrations.RemoveField(
            model_name='studentprofileinfo',
            name='spentPoints',
        ),
        migrations.RemoveField(
            model_name='studentprofileinfo',
            name='totalPoints',
        ),
    ]
