# Generated by Django 2.1.7 on 2019-11-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_auto_20191129_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofileinfo',
            name='StudentID',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
