# Generated by Django 3.0.2 on 2020-02-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_auto_20200219_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofileinfo',
            name='currentPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofileinfo',
            name='spentPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofileinfo',
            name='totalPoints',
            field=models.IntegerField(default=0),
        ),
    ]
