# Generated by Django 3.0.2 on 2020-02-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_avatars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='avatarID',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
