# Generated by Django 2.2.7 on 2019-12-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_auto_20191130_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofileinfo',
            name='StudentID',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
