# Generated by Django 3.0.2 on 2020-02-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_auto_20200205_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatars',
            name='pointsCost',
            field=models.IntegerField(default=0),
        ),
    ]
