# Generated by Django 2.1.7 on 2019-12-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_auto_20191127_1215'),
        ('points', '0006_auto_20191130_0223'),
    ]

    operations = [
    ]
