# Generated by Django 2.1.7 on 2020-02-29 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_auto_20200226_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofileinfo',
            name='profile_pic',
        ),
    ]
