# Generated by Django 3.0.2 on 2020-03-01 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0009_studentprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofileinfo',
            name='StudentID',
            field=models.CharField(help_text='Please enter your student ID you use for Moodle.', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofileinfo',
            name='user',
            field=models.OneToOneField(help_text='Please enter your own nickname.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
