# Generated by Django 2.1.7 on 2020-03-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0011_auto_20200301_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='static/images/avatar-default-icon.png', upload_to='profile_pics'),
        ),
    ]
