# Generated by Django 2.1.7 on 2020-03-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0012_auto_20200303_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/avatar-default-icon.png', upload_to='profile_pics'),
        ),
    ]
