# Generated by Django 2.1.7 on 2020-03-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0018_auto_20200312_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/avatar-default-icon.png', upload_to='profile_pics'),
        ),
    ]
