# Generated by Django 2.1.7 on 2020-03-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0020_auto_20200312_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='images/avatar-default-icon.png', upload_to='images'),
        ),
    ]
